[phases.setup]
nixPkgs = ["python311", "openjdk17"]

[phases.install]
cmds = ["cd backend && python -m pip install -r requirements.txt"]

[start]
cmd = "cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
