[phases.setup]
nixPkgs = ["python311", "jdk17", "apacheSpark"]

[phases.install]
cmds = [
    "python -m venv /opt/venv",
    ". /opt/venv/bin/activate && pip install --upgrade pip",
    ". /opt/venv/bin/activate && pip install -r backend/requirements.txt"
]

[start]
cmd = "source /opt/venv/bin/activate && uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT"
